import { createHash } from 'node:crypto';
import { items, record, text } from './catalog';
import type { ProjectSnapshot, SandboxViewState } from './shared/protocol';
import { SANDBOX_PROFILE_PATH } from './paths';

const strings = (value: unknown): string[] =>
  items(value).filter((entry): entry is string => typeof entry === 'string');

/** Core supplies the resolved scope; the host never reimplements glob matching. */
export function sandboxView(
  value: unknown,
  snapshot: ProjectSnapshot,
  mode: 'off' | 'on',
  display: 'selected' | 'all',
  profileDraft: boolean,
): SandboxViewState {
  const scope = record(record(value).sandbox);
  const profileExists = scope.profile_exists === true;
  const namespace = text(scope.namespace) || undefined;
  const selectedPipelines = strings(scope.resolved_pipelines);
  const allowedEnvironments = strings(scope.allowed_envs);
  const error = text(scope.error) || undefined;
  const environment = snapshot.context.environment;
  const environmentError =
    allowedEnvironments.length && !allowedEnvironments.includes(environment)
      ? `Environment ${environment} is not allowed by the team sandbox policy.`
      : undefined;
  const valid =
    profileExists && !!namespace && selectedPipelines.length > 0 && !error && !environmentError;
  return {
    mode,
    display,
    profilePath: SANDBOX_PROFILE_PATH,
    profileExists,
    profileSource: profileExists ? (profileDraft ? 'draft' : 'saved') : 'missing',
    namespace,
    patterns: strings(scope.patterns),
    selectedPipelines,
    totalPipelines: snapshot.pipelines.length,
    allowedEnvironments,
    environment,
    strategy: text(scope.strategy) || undefined,
    tablePattern: text(scope.table_pattern) || undefined,
    valid,
    error:
      error ??
      environmentError ??
      (!profileExists
        ? 'Create .lhp/profile.yaml to enable sandbox mode.'
        : selectedPipelines.length === 0
          ? 'The sandbox profile selects no pipelines.'
          : undefined),
    stale: snapshot.stale || snapshot.refreshState === 'failed',
    scopeComplete: valid && !snapshot.stale && snapshot.refreshState !== 'failed',
    previewParity: 'source-only',
  };
}

export function sandboxScopeIdentity(state: SandboxViewState): string {
  return createHash('sha256')
    .update(
      JSON.stringify([
        state.mode,
        state.environment,
        state.mode === 'on' ? state.namespace : null,
        state.mode === 'on' ? [...state.selectedPipelines].sort() : null,
        state.mode === 'on' ? state.patterns : null,
        state.mode === 'on' ? state.strategy : null,
        state.mode === 'on' ? state.tablePattern : null,
      ]),
    )
    .digest('base64url');
}

export interface OutputScopeRecord {
  identity: string;
  label: string;
  externalChange?: boolean;
}

export function outputScopeLabel(view: SandboxViewState, record: OutputScopeRecord): string {
  const scope = record.identity === sandboxScopeIdentity(view) ? '' : ' · scope changed';
  const contents = record.externalChange ? ' · current contents unknown (external changes)' : '';
  return `Last generated by extension: ${record.label}${scope}${contents}`;
}
