import { describe, expect, it } from 'vitest';
import { demoSnapshot } from '../../webview/src/demoFixture';
import { outputScopeLabel, sandboxScopeIdentity, sandboxView } from '../../src/sandboxState';

describe('sandbox scope projection', () => {
  const raw = {
    sandbox: {
      profile_exists: true,
      namespace: 'alice',
      patterns: ['bronze_*'],
      resolved_pipelines: ['bronze_load'],
      allowed_envs: ['dev'],
      strategy: 'table',
      table_pattern: '{namespace}_{table}',
    },
  };
  it('projects the canonical resolved names and draft provenance without changing scope for Show all', () => {
    const snapshot = demoSnapshot();
    const selected = sandboxView(raw, snapshot, 'on', 'selected', true);
    const all = sandboxView(raw, snapshot, 'on', 'all', true);
    expect(selected).toMatchObject({
      profilePath: '.lhp/profile.yaml',
      profileSource: 'draft',
      namespace: 'alice',
      selectedPipelines: ['bronze_load'],
      valid: true,
      strategy: 'table',
    });
    expect(sandboxScopeIdentity(selected)).toBe(sandboxScopeIdentity(all));
    expect(sandboxScopeIdentity({ ...all, mode: 'off' })).not.toBe(sandboxScopeIdentity(all));
  });
  it('keeps missing profiles and disallowed environments visibly blocked in On mode', () => {
    const snapshot = demoSnapshot();
    expect(
      sandboxView({ sandbox: { profile_exists: false } }, snapshot, 'on', 'selected', false),
    ).toMatchObject({ valid: false, profileSource: 'missing' });
    const prod = { ...snapshot, context: { ...snapshot.context, environment: 'prod' } };
    expect(sandboxView(raw, prod, 'on', 'selected', false).error).toMatch(/not allowed/);
  });
  it('describes generated output as historical provenance and flags external changes', () => {
    const view = sandboxView(raw, demoSnapshot(), 'on', 'selected', false);
    const identity = sandboxScopeIdentity(view);
    expect(outputScopeLabel(view, { identity, label: 'Sandbox alice: 1 pipeline, dev' })).toMatch(
      /^Last generated by extension:/,
    );
    expect(
      outputScopeLabel(view, {
        identity,
        label: 'Sandbox alice: 1 pipeline, dev',
        externalChange: true,
      }),
    ).toContain('current contents unknown');
    expect(
      outputScopeLabel(
        { ...view, namespace: 'bob' },
        { identity, label: 'Sandbox alice: 1 pipeline, dev' },
      ),
    ).toContain('scope changed');
  });
});
